workflows:
  flutter-app-build:
    name: Build Flutter App (Android, iOS & Web)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS (no code sign)
        script: flutter build ios --release --no-codesign

      - name: Build Web
        script: flutter build web --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
      - build/web/**

    publishing:
      email:
        recipients:
          - your@email.com
